' Auto-generated by transpile-roku.js <- src/components/HomeScene.tsx
' Playlet Pattern: Top Hero Spotlight Banner + Multi-row RowList carousel
' DO NOT EDIT -- edit the TypeScript source and re-run: npm run transpile

sub init()
    m.logTag = "HomeScene"
    LogInfo(m.logTag, "Initializing HomeScene (Playlet Layout)")

    m.rowList         = m.top.findNode("rowList")
    m.focusedTitle    = m.top.findNode("focusedTitle")
    m.focusedDesc     = m.top.findNode("focusedDesc")
    m.focusedRating   = m.top.findNode("focusedRating")
    m.focusedDuration = m.top.findNode("focusedDuration")
    m.focusedCategory = m.top.findNode("focusedCategory")
    m.focusedPoster   = m.top.findNode("focusedPoster")

    if m.rowList <> invalid
        ' RowList cell dimensions: 300 wide x 230 tall (poster 300x180 + text 50)
        m.rowList.rowItemSize    = [[300, 230]]
        m.rowList.rowItemSpacing = [[24, 0]]

        m.rowList.observeField("rowItemSelected", "onItemSelected")
        m.rowList.observeField("rowItemFocused", "onRowItemFocused")
    end if
end sub

' Populate RowList grid
sub onContentChanged()
    if m.top.content = invalid then return
    if m.rowList = invalid then return

    LogInfo(m.logTag, "Content received -- populating RowList")
    m.rowList.content = m.top.content

    m.rowList.setFocus(true)
    updateSpotlight([0, 0])
end sub

sub onRowItemFocused()
    if m.rowList = invalid then return
    focusedPos = m.rowList.rowItemFocused
    if focusedPos <> invalid
        updateSpotlight(focusedPos)
    end if
end sub

sub updateSpotlight(itemPos as Object)
    if m.top.content = invalid then return

    rowNode = m.top.content.getChild(itemPos[0])
    if rowNode = invalid then return

    video = rowNode.getChild(itemPos[1])
    if video = invalid then return

    if m.focusedTitle <> invalid then m.focusedTitle.text = video.title
    if m.focusedDesc <> invalid then m.focusedDesc.text = video.description
    if m.focusedRating <> invalid then m.focusedRating.text = video.rating
    if m.focusedCategory <> invalid then m.focusedCategory.text = video.category
    if m.focusedPoster <> invalid and video.hdPosterUrl <> invalid then m.focusedPoster.uri = video.hdPosterUrl

    if m.focusedDuration <> invalid and video.length <> invalid
        mins = Int(video.length / 60)
        secs = video.length Mod 60
        secStr = secs.toStr()
        if secs < 10 then secStr = "0" + secStr
        m.focusedDuration.text = mins.toStr() + ":" + secStr
    end if
end sub

' Item selected -> play video
sub onItemSelected(event as Object)
    selectedPos = event.getData()
    if m.top.content = invalid or selectedPos = invalid then return

    rowNode = m.top.content.getChild(selectedPos[0])
    if rowNode = invalid then return

    videoNode = rowNode.getChild(selectedPos[1])
    if videoNode <> invalid
        LogInfo(m.logTag, "Selected video: '" + videoNode.title + "'")
        m.top.selectedVideo = videoNode
    end if
end sub
