' Auto-generated by transpile-roku.js ← src/components/HomeScene.tsx
' Mirrors: RowList grid + right spotlight info panel + focus tracking
' DO NOT EDIT — edit the TypeScript source and re-run: npm run transpile
'
' React concept              → BrightScript equivalent
' ──────────────────────────────────────────────────────────────────────
' videos prop                → RowList.content (ContentNode tree)
' focusedIndex state         → rowItemFocused (RowList native, fires observer)
' focusedVideo (useMemo)     → updateSpotlight() called on rowItemFocused change
' onSelectVideo(video)       → m.top.selectedVideo = node (observeField in MainScene)
' playbackHistory            → (future: roRegistry)
' categories / category pills → (future: LabelList above RowList)

sub init()
    m.logTag = "HomeScene"
    LogInfo(m.logTag, "Initializing HomeScene")

    m.rowList          = m.top.findNode("rowList")
    m.countBadge       = m.top.findNode("countBadge")
    m.focusedTitle     = m.top.findNode("focusedTitle")
    m.focusedDesc      = m.top.findNode("focusedDesc")
    m.focusedRating    = m.top.findNode("focusedRating")
    m.focusedDuration  = m.top.findNode("focusedDuration")
    m.focusedCategory  = m.top.findNode("focusedCategory")
    m.focusedId        = m.top.findNode("focusedId")
    m.artistBg         = m.top.findNode("artistBg")
    m.artistSectionLabel = m.top.findNode("artistSectionLabel")
    m.artistName       = m.top.findNode("artistName")

    if m.rowList <> invalid
        ' Mirrors: onClick / onMouseEnter → select / focus
        m.rowList.observeField("rowItemSelected", "onItemSelected")
        ' Mirrors: setFocusedIndex(idx) on hover/d-pad → right panel update
        m.rowList.observeField("rowItemFocused", "onRowItemFocused")
    end if
end sub

' Mirrors: useEffect on videos prop change → populate RowList grid
' Called when MainScene sets homeScene.content after feed loads
sub onContentChanged()
    if m.top.content = invalid then return
    if m.rowList = invalid then return

    LogInfo(m.logTag, "Content received — populating RowList")
    m.rowList.content = m.top.content

    ' Count badge — mirrors "{videos.length} Titles"
    firstRow = m.top.content.getChild(0)
    if firstRow <> invalid and m.countBadge <> invalid
        count = firstRow.getChildCount()
        m.countBadge.text = count.toStr() + " Titles"
    end if

    ' Initial spotlight + focus — mirrors initial focusedIndex = 0
    m.rowList.setFocus(true)
    updateSpotlight([0, 0])
end sub

' Mirrors: setFocusedIndex(idx) — right panel spotlight update on d-pad move
sub onRowItemFocused()
    if m.rowList = invalid then return
    pos = m.rowList.rowItemFocused
    if pos <> invalid
        updateSpotlight(pos)
    end if
end sub

' Update spotlight panel with the currently focused video
' Mirrors: all the focusedVideo rendering in the lg:col-span-4 section of HomeScene.tsx
sub updateSpotlight(itemPos as Object)
    if m.top.content = invalid then return

    rowNode = m.top.content.getChild(itemPos[0])
    if rowNode = invalid then return

    video = rowNode.getChild(itemPos[1])
    if video = invalid then return

    ' Title — mirrors <h1>{focusedVideo.title}</h1>
    if m.focusedTitle <> invalid
        m.focusedTitle.text = video.title
    end if

    ' ID — mirrors "ID: {focusedVideo.id}"
    if m.focusedId <> invalid
        m.focusedId.text = "ID: " + video.id.toStr()
    end if

    ' Description — mirrors <p>{focusedVideo.description}</p>
    if m.focusedDesc <> invalid
        if video.description <> invalid and video.description <> ""
            m.focusedDesc.text = video.description
        else
            m.focusedDesc.text = "No description available."
        end if
    end if

    ' Rating — mirrors rating badge
    if m.focusedRating <> invalid
        if video.ratingValue <> invalid and video.ratingValue <> ""
            m.focusedRating.text = video.ratingValue
        else
            m.focusedRating.text = "G"
        end if
    end if

    ' Duration — mirrors formatDuration(focusedVideo.duration)
    if m.focusedDuration <> invalid
        dur = 0
        if video.length <> invalid then dur = video.length
        mins = int(dur / 60)
        secs = dur mod 60
        secsPrefix = ""
        if secs < 10 then secsPrefix = "0"
        m.focusedDuration.text = mins.toStr() + ":" + secsPrefix + secs.toStr()
    end if

    ' Category — mirrors category badge
    if m.focusedCategory <> invalid
        cat = ""
        if video.categories <> invalid and video.categories <> ""
            cat = video.categories
        else
            cat = "General"
        end if
        m.focusedCategory.text = cat
    end if

    ' Artist / Studio — mirrors artist card (conditionally visible)
    hasArtist = video.actors <> invalid and video.actors <> ""
    if m.artistBg <> invalid        then m.artistBg.visible = hasArtist
    if m.artistSectionLabel <> invalid then m.artistSectionLabel.visible = hasArtist
    if m.artistName <> invalid
        m.artistName.visible = hasArtist
        if hasArtist then m.artistName.text = video.actors
    end if
end sub

' Mirrors: onClick → onSelectVideo(video)
sub onItemSelected()
    if m.rowList = invalid or m.rowList.content = invalid then return
    pos = m.rowList.rowItemSelected
    if pos = invalid then return

    rowNode = m.rowList.content.getChild(pos[0])
    if rowNode = invalid then return

    video = rowNode.getChild(pos[1])
    if video = invalid then return

    LogInfo(m.logTag, "Video selected: " + video.title)
    ' Mirrors: onSelectVideo(video) → triggers MainScene.handleSelectVideo via observeField
    m.top.selectedVideo = video
end sub
