' Auto-generated by transpile-roku.js <- src/services/feedService.ts
' Mirrors: FeedService.loadFeed(feedUrl?) -- URL routing (local pkg vs HTTP)
' DO NOT EDIT -- edit the TypeScript source and re-run: npm run transpile

' Mirrors: static loadFeed(feedUrl?) URL selection
' Returns the pkg: local feed path or custom remote URL
function FeedService_GetFeedUrl() as String
    return "pkg:/feeds/sample-feed.json"
end function
