' Auto-generated by transpile-roku.js ← src/services/feedParser.ts
' Mirrors: FeedParser.parseFeed(rawData) → FeedData
'          FeedParser.normalizeVideoItem(item, index) → Video
'          FeedParser.normalizeRokuContentFeedItem(item, index) → Video
' Output: ContentNode tree (rootNode → rowNode → itemNodes) for RowList
' ContentNode fields mirror Video interface from src/types.ts
' DO NOT EDIT — edit the TypeScript source and re-run: npm run transpile

' ─────────────────────────────────────────────────────────────────────
' FALLBACK_MIRRORS — mirrors PlayerScene.tsx FALLBACK_MIRRORS array
' Used when no stream URL is found in feed item
' ─────────────────────────────────────────────────────────────────────
function FeedParser_FallbackStreams() as Object
    return [
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
    ]
end function

' ─────────────────────────────────────────────────────────────────────
' FeedParser_Parse — main entry point
' Mirrors: FeedParser.parseFeed(rawData: unknown): FeedData
' Detects feed format and routes to the correct normalizer
' ─────────────────────────────────────────────────────────────────────
function FeedParser_Parse(jsonString as String) as Object
    logTag = "FeedParser"
    LogInfo(logTag, "Starting feed parse — ContentNode tree construction")

    rootNode = CreateObject("roSGNode", "ContentNode")
    rowNode = rootNode.createChild("ContentNode")
    rowNode.title = "Featured Catalog"

    json = ParseJson(jsonString)
    if json = invalid
        LogError(logTag, "ParseJson failed — invalid JSON string")
        return rootNode
    end if

    items = []

    ' Format 0: Root-level array [ { title, url, ... } ]
    ' Mirrors: if (Array.isArray(parsed)) items = parsed
    if type(json) = "roArray"
        LogInfo(logTag, "Detected root-level array (" + json.count().toStr() + " items)")
        items = json

    ' Format 1: Simple { "videos": [...] }
    ' Mirrors: else if (Array.isArray(parsed.videos)) items = parsed.videos
    else if type(json) = "roAssociativeArray" and json.videos <> invalid and type(json.videos) = "roArray"
        LogInfo(logTag, "Detected videos array (" + json.videos.count().toStr() + " items)")
        items = json.videos

    ' Format 2: Roku Content Feed { "movie":[...], "shortFormVideos":[...], ... }
    ' Mirrors: else if (Array.isArray(parsed.shortFormVideos) || ...)
    else if type(json) = "roAssociativeArray" and (json.movie <> invalid or json.shortFormVideos <> invalid or json.tvSpecial <> invalid)
        LogInfo(logTag, "Detected Roku Content Feed schema")
        if json.movie <> invalid and type(json.movie) = "roArray"
            for each item in json.movie
                items.push(item)
            end for
        end if
        if json.shortFormVideos <> invalid and type(json.shortFormVideos) = "roArray"
            for each item in json.shortFormVideos
                items.push(item)
            end for
        end if
        if json.tvSpecial <> invalid and type(json.tvSpecial) = "roArray"
            for each item in json.tvSpecial
                items.push(item)
            end for
        end if

    ' Fallback: search all keys for first array — mirrors the fallback loop
    else if type(json) = "roAssociativeArray"
        LogWarn(logTag, "Unrecognized feed structure — searching all array keys")
        for each key in json
            if type(json[key]) = "roArray"
                items = json[key]
                LogInfo(logTag, "Found array under key: " + key)
                exit for
            end if
        end for
    end if

    LogInfo(logTag, "Normalizing " + items.count().toStr() + " feed items → ContentNodes")
    fallbacks = FeedParser_FallbackStreams()

    for i = 0 to items.count() - 1
        item = items[i]
        if item = invalid then goto nextItem

        node = FeedParser_NormalizeItem(item, i, fallbacks)
        if node <> invalid
            rowNode.appendChild(node)
        end if

        nextItem:
    end for

    LogInfo(logTag, "ContentNode tree built: " + rowNode.getChildCount().toStr() + " items in row")
    return rootNode
end function

' ─────────────────────────────────────────────────────────────────────
' FeedParser_NormalizeItem
' Mirrors: normalizeVideoItem(item, index) → Video
' Maps raw JSON item fields to ContentNode fields (Video interface)
' ─────────────────────────────────────────────────────────────────────
function FeedParser_NormalizeItem(item as Object, idx as Integer, fallbacks as Object) as Object
    node = CreateObject("roSGNode", "ContentNode")

    ' id — mirrors: String(item.id || item.imdbID || item.guid || `vid-N`)
    if item.id <> invalid
        node.id = item.id.toStr()
    else if item.imdbID <> invalid
        node.id = item.imdbID.toStr()
    else
        node.id = "vid-" + (idx + 1).toStr()
    end if

    ' title — mirrors: item.title || item.Title || item.name || "Video #N"
    if item.title <> invalid and item.title <> ""
        node.title = item.title
    else if item.Title <> invalid
        node.title = item.Title
    else if item.name <> invalid
        node.name = item.name
    else
        node.title = "Video #" + (idx + 1).toStr()
    end if

    ' thumbnail → HDPosterUrl — mirrors: item.thumbnail || item.poster || item.Poster || fallback
    if item.thumbnail <> invalid and item.thumbnail <> ""
        node.HDPosterUrl = item.thumbnail
    else if item.poster <> invalid and item.poster <> ""
        node.HDPosterUrl = item.poster
    else if item.Poster <> invalid and item.Poster <> ""
        node.HDPosterUrl = item.Poster
    else if item.imageUrl <> invalid
        node.HDPosterUrl = item.imageUrl
    else
        node.HDPosterUrl = "https://images.unsplash.com/photo-1574063413132-355dbfd83e0c?w=800"
    end if

    ' url → stream URL — mirrors: item.url || item.streamUrl || item.contentUrl || fallback
    if item.url <> invalid and item.url <> ""
        node.url = item.url
    else if item.streamUrl <> invalid and item.streamUrl <> ""
        node.url = item.streamUrl
    else if item.contentUrl <> invalid
        node.url = item.contentUrl
    else if item.content <> invalid and type(item.content) = "roAssociativeArray"
        ' Roku Content Feed: content.videos[0].url
        if item.content.videos <> invalid and type(item.content.videos) = "roArray" and item.content.videos.count() > 0
            node.url = item.content.videos[0].url.toStr()
        else if item.content.url <> invalid
            node.url = item.content.url.toStr()
        end if
    end if

    if node.url = invalid or node.url = ""
        node.url = fallbacks[idx mod fallbacks.count()]
    end if

    node.streamFormat = "mp4"

    ' description — mirrors: item.description || item.Plot || item.plot || fallback
    if item.description <> invalid and item.description <> ""
        node.description = item.description
    else if item.Plot <> invalid
        node.description = item.Plot
    else if item.shortDescription <> invalid
        node.description = item.shortDescription
    else
        node.description = "No description provided."
    end if

    ' duration → length (seconds) — mirrors: typeof item.duration === 'number' ? item.duration : parse Runtime
    if item.duration <> invalid and type(item.duration) = "roInteger"
        node.length = item.duration
    else if item.duration <> invalid and type(item.duration) = "roFloat"
        node.length = int(item.duration)
    else
        node.length = 120
    end if

    ' category → categories — mirrors: item.category || Genre.split(",")[0]
    if item.category <> invalid and item.category <> ""
        node.categories = item.category
    else if item.Genre <> invalid
        ' Take first genre from comma-separated list
        genres = item.Genre.split(",")
        firstGenre = genres[0]
        node.categories = firstGenre
    else if item.genre <> invalid
        node.categories = item.genre
    else if item.genres <> invalid and type(item.genres) = "roArray" and item.genres.count() > 0
        node.categories = item.genres[0].toStr()
    else
        node.categories = "General"
    end if

    ' rating → ratingValue — mirrors: item.rating || item.Rated
    if item.rating <> invalid and item.rating <> ""
        if type(item.rating) = "roAssociativeArray" and item.rating.rating <> invalid
            node.ratingValue = item.rating.rating.toStr()
        else
            node.ratingValue = item.rating.toStr()
        end if
    else if item.Rated <> invalid
        node.ratingValue = item.Rated.toStr()
    else
        node.ratingValue = "G"
    end if

    ' releaseDate — mirrors: item.releaseDate || item.Year || item.Released
    if item.releaseDate <> invalid
        node.releaseDate = item.releaseDate.toStr()
    else if item.Year <> invalid
        node.releaseDate = item.Year.toStr()
    else if item.Released <> invalid
        node.releaseDate = item.Released.toStr()
    end if

    ' artist → actors — mirrors: item.artist || item.Director || item.Writer
    if item.artist <> invalid and item.artist <> ""
        node.actors = item.artist
    else if item.Director <> invalid and item.Director <> ""
        node.actors = item.Director
    else if item.Writer <> invalid
        node.actors = item.Writer
    end if

    return node
end function
