' Auto-generated by transpile-roku.js <- src/components/MainScene.tsx
' Mirrors: App root state machine -- feed loading + HOME/PLAYER scene switching
' DO NOT EDIT -- edit the TypeScript source and re-run: npm run transpile
'
' React concept         -> BrightScript equivalent
' --------------------------------------------------------------------------
' useState('HOME')      -> homeScene.visible / playerScene.visible toggle
' useState(null)        -> homeScene.content (ContentNode from Task)
' useState(null)        -> playerScene.content (selected video ContentNode)
' useState(true)        -> loadingOverlay.visible
' useState(null)        -> errorOverlay.visible + errorMessageLabel.text
' useEffect([], init)   -> sub init() -> loadContentFeed()
' async fetchFeed()     -> LoadFeedTask node (runs off render thread)
' handleSelectVideo     -> onVideoSelected() (observeField on homeScene)
' handleBackToHome      -> navigateToHome() (called from key event or player state)
' global keydown        -> onKeyEvent(key, press)

sub init()
    m.logTag = "MainScene"
    LogInfo(m.logTag, "Initializing MainScene -- Roku SceneGraph Channel")

    ' Cache node refs -- mirrors useRef / DOM refs
    m.homeScene          = m.top.findNode("homeScene")
    m.playerScene        = m.top.findNode("playerScene")
    m.loadingOverlay     = m.top.findNode("loadingOverlay")
    m.errorOverlay       = m.top.findNode("errorOverlay")
    m.errorMessageLabel  = m.top.findNode("errorMessageLabel")

    ' Mirrors: observeField for selectedVideo -> handleSelectVideo(video)
    if m.homeScene <> invalid
        m.homeScene.observeField("selectedVideo", "onVideoSelected")
    end if

    ' Mirrors: state "finished"|"error" -> handleBackToHome()
    if m.playerScene <> invalid
        m.playerScene.observeField("state", "onPlayerStateChanged")
    end if

    ' Mirrors: useEffect(() => fetchFeed(feedUrl), [fetchFeed, feedUrl])
    loadContentFeed()
end sub

' Mirrors: async function fetchFeed(url: string)
' Creates LoadFeedTask node and starts it -- equivalent to initiating an async fetch
sub loadContentFeed()
    LogInfo(m.logTag, "Creating LoadFeedTask -- mirrors async fetchFeed()")

    m.feedTask = CreateObject("roSGNode", "LoadFeedTask")
    if m.feedTask = invalid
        showError("Failed to create LoadFeedTask node")
        return
    end if

    m.feedTask.url = FeedService_GetFeedUrl()

    ' Mirrors: .then(data => setFeedData(data))
    m.feedTask.observeField("content", "onFeedLoaded")
    ' Mirrors: .catch(err => setErrorMsg(err.message))
    m.feedTask.observeField("errorMessage", "onFeedError")

    ' Mirrors: setIsLoading(true)
    if m.loadingOverlay <> invalid then m.loadingOverlay.visible = true

    ' Mirrors: await fetch() -- kicks off Task execution in worker thread
    m.feedTask.control = "RUN"
end sub

' Mirrors: .then(data => { setFeedData(data); setIsLoading(false) })
sub onFeedLoaded()
    if m.feedTask = invalid then return
    if m.feedTask.content = invalid then return

    LogInfo(m.logTag, "Feed loaded -- setting HomeScene content")

    ' Mirrors: setFeedData(data) -> passes ContentNode tree to HomeScene
    if m.homeScene <> invalid
        m.homeScene.content = m.feedTask.content
    end if

    ' Mirrors: setIsLoading(false) + setErrorMsg(null)
    if m.loadingOverlay <> invalid then m.loadingOverlay.visible = false
    if m.errorOverlay <> invalid then m.errorOverlay.visible = false

    ' Initial focus -- mirrors: HomeScene receives focus after load
    if m.homeScene <> invalid
        m.homeScene.setFocus(true)
    end if
end sub

' Mirrors: .catch(err => { setErrorMsg(err.message); setIsLoading(false) })
sub onFeedError()
    if m.feedTask = invalid then return
    errMsg = m.feedTask.errorMessage
    if errMsg <> "" and errMsg <> invalid
        showError(errMsg)
    end if
end sub

sub showError(msg as String)
    LogError(m.logTag, "Feed load error: " + msg)
    if m.loadingOverlay <> invalid  then m.loadingOverlay.visible = false
    if m.errorOverlay <> invalid    then m.errorOverlay.visible = true
    if m.errorMessageLabel <> invalid then m.errorMessageLabel.text = msg
end sub

' Mirrors: handleSelectVideo(video) -> setSelectedVideo(video) + setCurrentScene('PLAYER')
sub onVideoSelected()
    if m.homeScene = invalid then return
    selectedVideo = m.homeScene.selectedVideo
    if selectedVideo = invalid then return

    LogInfo(m.logTag, "Navigating to PlayerScene: " + selectedVideo.title)

    ' Mirrors: setCurrentScene('PLAYER') -- hide HOME, show PLAYER
    m.homeScene.visible  = false
    if m.playerScene <> invalid
        m.playerScene.content  = selectedVideo
        m.playerScene.visible  = true
        m.playerScene.setFocus(true)
    end if
end sub

' Mirrors: state "finished"|"error" -> handleBackToHome()
sub onPlayerStateChanged()
    if m.playerScene = invalid then return
    state = m.playerScene.state
    LogInfo(m.logTag, "Player state: " + state)
    if state = "finished" or state = "error"
        navigateToHome()
    end if
end sub

' Mirrors: handleBackToHome() -> setCurrentScene('HOME')
sub navigateToHome()
    LogInfo(m.logTag, "Returning to HomeScene -- mirrors handleBackToHome()")
    if m.playerScene <> invalid
        m.playerScene.control = "stop"
        m.playerScene.visible = false
    end if
    if m.homeScene <> invalid
        m.homeScene.visible = true
        m.homeScene.setFocus(true)
    end if
end sub

' Mirrors: global keydown listener (Escape/Backspace -> back from PLAYER)
function onKeyEvent(key as String, press as Boolean) as Boolean
    if not press then return false
    if key = "back"
        if m.playerScene <> invalid and m.playerScene.visible
            LogInfo(m.logTag, "Back key -- navigating to HomeScene")
            navigateToHome()
            return true
        end if
    end if
    return false
end function
