' Auto-generated by transpile-roku.js <- app.config.json + src/utils/config.ts
' DO NOT EDIT -- edit the TypeScript source and re-run: npm run transpile

function GetRokuConfig() as Object
    return {
        appName:            "Personal TV",
        appSubtitle:        "Enjoy your videos",
        version:            "1.0.0",
        devMode:            true,
        wifiCheckIntervalMs: 120000,
        defaultFeedUrl:     "pkg:/feeds/sample-feed.json"
    }
end function
