' Auto-generated by transpile-roku.js <- src/utils/logger.ts
' Mirrors: Logger class createEntry(level, module, message)
' Uses standalone global subs -- avoids BrightScript compile errors from anonymous
' sub closures that reference the SceneGraph component namespace via m.
' Usage: m.logTag = "Tag" / LogInfo(m.logTag, "message")
' DO NOT EDIT -- edit the TypeScript source and re-run: npm run transpile

sub LogInfo(tag as String, msg as String)
    print "[INFO ][" + tag + "] " + msg
end sub

sub LogWarn(tag as String, msg as String)
    print "[WARN ][" + tag + "] " + msg
end sub

sub LogError(tag as String, msg as String)
    print "[ERROR][" + tag + "] " + msg
end sub

sub LogDebug(tag as String, msg as String)
    print "[DEBUG][" + tag + "] " + msg
end sub
