' Auto-generated by transpile-roku.js ← src/utils/logger.ts
' Mirrors: class Logger { createEntry(level, module, message) }
'       → factory function returning AA with info/warn/error/debug subs
' BrightScript note: inside an AA sub, `m` refers to the AA (the receiver), not the component.
' DO NOT EDIT — edit the TypeScript source and re-run: npm run transpile

function Logger(moduleName as String) as Object
    return {
        module: moduleName,
        info: sub(msg as String)
            print "[INFO ][" + m.module + "] " + msg
        end sub,
        warn: sub(msg as String)
            print "[WARN ][" + m.module + "] " + msg
        end sub,
        error: sub(msg as String)
            print "[ERROR][" + m.module + "] " + msg
        end sub,
        debug: sub(msg as String)
            print "[DEBUG][" + m.module + "] " + msg
        end sub
    }
end function
