' Auto-generated by transpile-roku.js ← HomeScene.tsx video card rendering
' Mirrors: <motion.div> card with poster/title/category/focus ring/play overlay
' DO NOT EDIT — edit the TypeScript source and re-run: npm run transpile

sub init()
    m.poster       = m.top.findNode("poster")
    m.title        = m.top.findNode("title")
    m.category     = m.top.findNode("category")
    m.rating       = m.top.findNode("rating")
    m.focusBorder  = m.top.findNode("focusBorder")
    m.focusGradient = m.top.findNode("focusGradient")
    m.playIcon     = m.top.findNode("playIcon")
end sub

' Mirrors: card re-render when video prop changes
' Populates all visual fields from ContentNode (mirrors Video interface fields)
sub onItemContentChanged()
    item = m.top.itemContent
    if item = invalid then return

    ' title — mirrors video.title
    if item.title <> invalid and item.title <> ""
        m.title.text = item.title
    end if

    ' HDPosterUrl — mirrors <img src={video.thumbnail}>
    if item.HDPosterUrl <> invalid and item.HDPosterUrl <> ""
        m.poster.uri = item.HDPosterUrl
    end if

    ' categories — mirrors <span>{video.category}</span>
    if item.categories <> invalid and item.categories <> ""
        m.category.text = item.categories
    else
        m.category.text = "General"
    end if

    ' ratingValue — mirrors rating badge
    if item.ratingValue <> invalid and item.ratingValue <> ""
        m.rating.text = item.ratingValue
    end if
end sub

' Mirrors: isFocused CSS classes — border-[#9e46ea] ring-4 scale-[1.02] when focused
' focusPercent transitions 0.0→1.0 as RowList animates focus between items
sub onFocusPercentChanged()
    focused = (m.top.focusPercent > 0.5)

    m.focusBorder.visible  = focused
    m.focusGradient.visible = focused
    m.playIcon.visible     = focused

    ' Mirrors: text-white font-bold when isFocused vs text-gray-200
    if focused
        m.title.color = "0xFFFFFFFF"
    else
        m.title.color = "0xE5E7EBFF"
    end if
end sub
